### ISSUE TITLE
Export use as a property

### ISSUE THREAD

**Issue by hadess** [knuesel/gst-airplay#3]
It would be super useful for building applications to know whether there's a client connected or not, so that the application could show a "rest" screen and only switch when a connection has been made.

**Comment by sijow** [comment]
There is now a `connected` property that should provide the desired information.

**Comment by sijow** [comment]
(BTW it seems the airplay library emits duplicate events, so if you register a callback for property changes it will be called twice for each change.)

**Comment by hadess** [comment]
You could do `if (self->connected) return;` if `conn_init()` (and similar in `conn_destroy()`) although it's just an small optimisation.

That'll be useful though, thanks!

**Comment by sijow** [comment]
Good idea, this is done in the latest commit (which also ensures the boolean flag is properly synchronized between threads).
